name: Labelbox Notebooks Rye Setup

inputs:
  python-version:
    required: true

runs:
  using: "composite"
  steps:
    - name: Install the latest version of rye
      uses: eifinger/setup-rye@v4
      with:
        enable-cache: true
    - name: Rye Setup
      shell: bash
      run: |
        rye config --set-bool behavior.use-uv=true
    - name: Python setup
      shell: bash
      run: rye pin ${{ inputs.python-version }}
    - name: Environment setup
      shell: bash
      run: |
        rye sync -f --update-all
