name: ReadMe GitHub Action 🦉

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - README.md

jobs:
  custompages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions
        with:
          python-version: 3.12
      - name: Create readme
        run: rye run create-doc-readme
      - name: Run `custompages` command
        uses: readmeio/rdme@v8
        with:
          rdme: custompages ./tutorials.html --key=${{ secrets.README_API_KEY }}
